version: "3.8"

services:
  frontend:
    image: node:20-alpine
    volumes:
      - ./frontend:/frontend
    ports:
      - 5173:5173
    working_dir: /frontend
    command: npm run setup

  backend:
    build: ./backend
    ports:
      - 3000:3000
    volumes:
      - ./backend:/backend
      - /backend/node_modules
    command: npx json-server data.json --host 0.0.0.0 -m ./node_modules/jeremy-json-server-auth